//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDocs.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DNDocs.Web.Resources.DefaultResources", typeof(DefaultResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Directory.
        /// </summary>
        internal static string AddDirectory {
            get {
                return ResourceManager.GetString("AddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File.
        /// </summary>
        internal static string AddFile {
            get {
                return ResourceManager.GetString("AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add md file.
        /// </summary>
        internal static string AddMdFile {
            get {
                return ResourceManager.GetString("AddMdFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string AddNewTopic {
            get {
                return ResourceManager.GetString("AddNewTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin - Dashboard.
        /// </summary>
        internal static string AdminDashboard {
            get {
                return ResourceManager.GetString("AdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Projects.
        /// </summary>
        internal static string AllProjects {
            get {
                return ResourceManager.GetString("AllProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Robinia Docs Projects.
        /// </summary>
        internal static string AllRobiniaDocsProjects {
            get {
                return ResourceManager.GetString("AllRobiniaDocsProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Action Completed.
        /// </summary>
        internal static string AuthenticationActionCompleted {
            get {
                return ResourceManager.GetString("AuthenticationActionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete page because page does not exists.
        /// </summary>
        internal static string CannotDeletePageBecauseItDoesNotExist {
            get {
                return ResourceManager.GetString("CannotDeletePageBecauseItDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete topic because it has one or more children. Delete children first..
        /// </summary>
        internal static string CannotDeleteTopicBecauseItHasChildren {
            get {
                return ResourceManager.GetString("CannotDeleteTopicBecauseItHasChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete topic because topic does not exists.
        /// </summary>
        internal static string CannotDeleteTopicDoesNotExists {
            get {
                return ResourceManager.GetString("CannotDeleteTopicDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to confirm delete project.
        /// </summary>
        internal static string CheckToConfirmHardDeleteProject {
            get {
                return ResourceManager.GetString("CheckToConfirmHardDeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You sure you want to delete Topic with Id: &apos;{0}&apos;?.
        /// </summary>
        internal static string ConfirmDeleteTopicDialogTemplate {
            get {
                return ResourceManager.GetString("ConfirmDeleteTopicDialogTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You sure You want to delete Topic: &apos;{0}&apos;?.
        /// </summary>
        internal static string ConfirmDialog_DeleteTopicMessageTemplate {
            get {
                return ResourceManager.GetString("ConfirmDialog_DeleteTopicMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Items.
        /// </summary>
        internal static string ContentItems {
            get {
                return ResourceManager.GetString("ContentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content has been updated successfully.
        /// </summary>
        internal static string ContentUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ContentUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie Consent.
        /// </summary>
        internal static string CookieConsent {
            get {
                return ResourceManager.GetString("CookieConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies &amp; Privacy.
        /// </summary>
        internal static string CookiesAndPrivacy {
            get {
                return ResourceManager.GetString("CookiesAndPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create / Edit Page Details.
        /// </summary>
        internal static string CreateEditPageDetails {
            get {
                return ResourceManager.GetString("CreateEditPageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create / Edit Topic Details.
        /// </summary>
        internal static string CreateEditTopicDetails {
            get {
                return ResourceManager.GetString("CreateEditTopicDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new topic.
        /// </summary>
        internal static string CreateNewTopic {
            get {
                return ResourceManager.GetString("CreateNewTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create another page.
        /// </summary>
        internal static string CreateOtherPage {
            get {
                return ResourceManager.GetString("CreateOtherPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Another Topic.
        /// </summary>
        internal static string CreateOtherTopic {
            get {
                return ResourceManager.GetString("CreateOtherTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new page.
        /// </summary>
        internal static string CreatePage {
            get {
                return ResourceManager.GetString("CreatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        internal static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declared in.
        /// </summary>
        internal static string DeclaredIn {
            get {
                return ResourceManager.GetString("DeclaredIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaring type.
        /// </summary>
        internal static string DeclaringType {
            get {
                return ResourceManager.GetString("DeclaringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete project.
        /// </summary>
        internal static string DeleteProject {
            get {
                return ResourceManager.GetString("DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Topic.
        /// </summary>
        internal static string DeleteTopic {
            get {
                return ResourceManager.GetString("DeleteTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory name.
        /// </summary>
        internal static string DirectoryName {
            get {
                return ResourceManager.GetString("DirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docfx editor.
        /// </summary>
        internal static string DocfxEditor {
            get {
                return ResourceManager.GetString("DocfxEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Content.
        /// </summary>
        internal static string EditContent {
            get {
                return ResourceManager.GetString("EditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Details.
        /// </summary>
        internal static string EditDetails {
            get {
                return ResourceManager.GetString("EditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit File Content.
        /// </summary>
        internal static string EditFileContent {
            get {
                return ResourceManager.GetString("EditFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Page.
        /// </summary>
        internal static string EditPage {
            get {
                return ResourceManager.GetString("EditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Page Content.
        /// </summary>
        internal static string EditPageContent {
            get {
                return ResourceManager.GetString("EditPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Properties.
        /// </summary>
        internal static string EditProperties {
            get {
                return ResourceManager.GetString("EditProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underlying Type.
        /// </summary>
        internal static string EnumUnderlyingType {
            get {
                return ResourceManager.GetString("EnumUnderlyingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete page because it has related objects. Go to edit page and clear all related objects.
        /// </summary>
        internal static string Error_CantDeletePageHasRelatedObjects {
            get {
                return ResourceManager.GetString("Error_CantDeletePageHasRelatedObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot request more than 5 projects (five requests on queue).
        ///Please wait for deploy of at least one project .
        /// </summary>
        internal static string ErrorMoreThanFiveProjectsRequested {
            get {
                return ResourceManager.GetString("ErrorMoreThanFiveProjectsRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event type.
        /// </summary>
        internal static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore all projects hosted on RobiniaDocs.
        /// </summary>
        internal static string ExploreAllRobiniaDocsProjects {
            get {
                return ResourceManager.GetString("ExploreAllRobiniaDocsProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore API Objects.
        /// </summary>
        internal static string ExploreAPIObjects {
            get {
                return ResourceManager.GetString("ExploreAPIObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must contains only *.dll file and cannot contain files from &apos;Project files&apos; form field above.
        /// </summary>
        internal static string FieldError_ProjectDependsOnFiles_InvalidBinaryFile {
            get {
                return ResourceManager.GetString("FieldError_ProjectDependsOnFiles_InvalidBinaryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robinia Url prefix must not be empty, must consist only of small letters &apos;a&apos; - &apos;z&apos;, length cannot be greated that 16 characters.
        /// </summary>
        internal static string FieldError_RobiniaUrlPrefix {
            get {
                return ResourceManager.GetString("FieldError_RobiniaUrlPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field value.
        /// </summary>
        internal static string FieldValue {
            get {
                return ResourceManager.GetString("FieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose files or drag and drop files here.
        /// </summary>
        internal static string FileUpl_DragDropMessage {
            get {
                return ResourceManager.GetString("FileUpl_DragDropMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files count: {0}.
        /// </summary>
        internal static string FileUpl_FilesCount {
            get {
                return ResourceManager.GetString("FileUpl_FilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files from disk.
        /// </summary>
        internal static string FileUpl_SelectFilesButtonText {
            get {
                return ResourceManager.GetString("FileUpl_SelectFilesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploader.
        /// </summary>
        internal static string FileUploader {
            get {
                return ResourceManager.GetString("FileUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET assembly files (.dll, .xml).
        /// </summary>
        internal static string Form_Project_BlobFilesFieldName {
            get {
                return ResourceManager.GetString("Form_Project_BlobFilesFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Url.
        /// </summary>
        internal static string Form_Project_GithubProjectUrl {
            get {
                return ResourceManager.GetString("Form_Project_GithubProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Form_Project_ProjectDescription {
            get {
                return ResourceManager.GetString("Form_Project_ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        internal static string Form_Project_ProjectName {
            get {
                return ResourceManager.GetString("Form_Project_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robinia Url Prefix.
        /// </summary>
        internal static string Form_Project_RobiniaUrlPrefix {
            get {
                return ResourceManager.GetString("Form_Project_RobiniaUrlPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value required.
        /// </summary>
        internal static string FormFieldRequired {
            get {
                return ResourceManager.GetString("FormFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only *.dll .NET Core file that project depends on (Include e.g. all installed nuget .dlls. Do not include SDK&apos;s libs like System.*, do not include *.xml, do not include project files).
        /// </summary>
        internal static string FormRequestProject_ProjectDependsOnDlls {
            get {
                return ResourceManager.GetString("FormRequestProject_ProjectDependsOnDlls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project .NET Core *.dll and *.xml files (do not include any dependencies).
        /// </summary>
        internal static string FormRequestProject_ProjectFiles {
            get {
                return ResourceManager.GetString("FormRequestProject_ProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Topic.
        /// </summary>
        internal static string FormTitle_CreateNewTopic {
            get {
                return ResourceManager.GetString("FormTitle_CreateNewTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Topic Details.
        /// </summary>
        internal static string FormTitle_EditTopicProperties {
            get {
                return ResourceManager.GetString("FormTitle_EditTopicProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github Url.
        /// </summary>
        internal static string GithubUrl {
            get {
                return ResourceManager.GetString("GithubUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RobiniaDocs - Free online .NET Core documentation hosting platform.
        /// </summary>
        internal static string GlobalHeader_LinkTitle {
            get {
                return ResourceManager.GetString("GlobalHeader_LinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use.
        /// </summary>
        internal static string HowToUse {
            get {
                return ResourceManager.GetString("HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Projects hosted on RobiniaDocs.
        /// </summary>
        internal static string HtmlTitle_Home_AllProjects {
            get {
                return ResourceManager.GetString("HtmlTitle_Home_AllProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free .NET Core documentation platform.
        /// </summary>
        internal static string HtmlTitle_Home_Index {
            get {
                return ResourceManager.GetString("HtmlTitle_Home_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherits from.
        /// </summary>
        internal static string InheritsFrom {
            get {
                return ResourceManager.GetString("InheritsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order value. Min: 0, Max: Count of sibling topics (in current parent).
        /// </summary>
        internal static string InvalidTopicOrder {
            get {
                return ResourceManager.GetString("InvalidTopicOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last High Priority Logs.
        /// </summary>
        internal static string LastHighPriorityLogs {
            get {
                return ResourceManager.GetString("LastHighPriorityLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Logs.
        /// </summary>
        internal static string LastLogs {
            get {
                return ResourceManager.GetString("LastLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location - Object.
        /// </summary>
        internal static string LocationObjects {
            get {
                return ResourceManager.GetString("LocationObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location - Topic.
        /// </summary>
        internal static string LocationTopic {
            get {
                return ResourceManager.GetString("LocationTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Success.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Github.
        /// </summary>
        internal static string LoginWithGithub {
            get {
                return ResourceManager.GetString("LoginWithGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout success.
        /// </summary>
        internal static string LogoutSuccess {
            get {
                return ResourceManager.GetString("LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Pages.
        /// </summary>
        internal static string ManagePages {
            get {
                return ResourceManager.GetString("ManagePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Project.
        /// </summary>
        internal static string ManageProject {
            get {
                return ResourceManager.GetString("ManageProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Topics.
        /// </summary>
        internal static string ManageTopics {
            get {
                return ResourceManager.GetString("ManageTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of description is 1024 characters.
        /// </summary>
        internal static string Model_TopicDescriptionMaxLength1024 {
            get {
                return ResourceManager.GetString("Model_TopicDescriptionMaxLength1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Short name exceeds 64 characters.
        /// </summary>
        internal static string Model_TopicShortLengthMax64 {
            get {
                return ResourceManager.GetString("Model_TopicShortLengthMax64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Short Name is required.
        /// </summary>
        internal static string Model_TopicShortNameRequired {
            get {
                return ResourceManager.GetString("Model_TopicShortNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        internal static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        internal static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all nodes were selected. First 100 children selected, for more expand each not selected node and select again.
        /// </summary>
        internal static string NotAllNodesSelectedLimit100 {
            get {
                return ResourceManager.GetString("NotAllNodesSelectedLimit100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No values.
        /// </summary>
        internal static string NoValue {
            get {
                return ResourceManager.GetString("NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuget Package Name.
        /// </summary>
        internal static string NugetPackageName {
            get {
                return ResourceManager.GetString("NugetPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object explorer.
        /// </summary>
        internal static string ObjectExplorer {
            get {
                return ResourceManager.GetString("ObjectExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object informations.
        /// </summary>
        internal static string ObjectInformations {
            get {
                return ResourceManager.GetString("ObjectInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object name.
        /// </summary>
        internal static string ObjectName {
            get {
                return ResourceManager.GetString("ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object was not found.
        /// </summary>
        internal static string ObjectNotFound_NotFoundTitle {
            get {
                return ResourceManager.GetString("ObjectNotFound_NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page created successfully.
        /// </summary>
        internal static string PageCreatedSuccessfully {
            get {
                return ResourceManager.GetString("PageCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page has been deleted successfully.
        /// </summary>
        internal static string PageDeletedSuccessfully {
            get {
                return ResourceManager.GetString("PageDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page has been updated successfully.
        /// </summary>
        internal static string PageUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("PageUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page with specified Id was not found. Cannot edit page..
        /// </summary>
        internal static string PageWithSpecifiedIdWasNotFoundCannotEdit {
            get {
                return ResourceManager.GetString("PageWithSpecifiedIdWasNotFoundCannotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Topic.
        /// </summary>
        internal static string ParentTopic {
            get {
                return ResourceManager.GetString("ParentTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent topic cannot be topic child.
        /// </summary>
        internal static string ParentTopicCannotBeTopicChild {
            get {
                return ResourceManager.GetString("ParentTopicCannotBeTopicChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent topic does not exists.
        /// </summary>
        internal static string ParentTopicDoesNotExists {
            get {
                return ResourceManager.GetString("ParentTopicDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent topic id.
        /// </summary>
        internal static string ParentTopicId {
            get {
                return ResourceManager.GetString("ParentTopicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems.
        /// </summary>
        internal static string Problems {
            get {
                return ResourceManager.GetString("Problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Content.
        /// </summary>
        internal static string ProjectContent {
            get {
                return ResourceManager.GetString("ProjectContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project has been created successfully.
        /// </summary>
        internal static string ProjectCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ProjectCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Project.
        /// </summary>
        internal static string ProjectManage {
            get {
                return ResourceManager.GetString("ProjectManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name is required.
        /// </summary>
        internal static string ProjectNameRequired {
            get {
                return ResourceManager.GetString("ProjectNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project name is already in use. Please select other project name because it must be unique.
        /// </summary>
        internal static string ProjectNameUniqueAndNotEmpty {
            get {
                return ResourceManager.GetString("ProjectNameUniqueAndNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Requested Successfully.
        /// </summary>
        internal static string ProjectRequestedSuccessfully {
            get {
                return ResourceManager.GetString("ProjectRequestedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arctium.
        /// </summary>
        internal static string ProjectShortName {
            get {
                return ResourceManager.GetString("ProjectShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild needed.
        /// </summary>
        internal static string RebuildNeeded {
            get {
                return ResourceManager.GetString("RebuildNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect URL.
        /// </summary>
        internal static string RedirectUrl {
            get {
                return ResourceManager.GetString("RedirectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflected type.
        /// </summary>
        internal static string ReflectedType {
            get {
                return ResourceManager.GetString("ReflectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Directory.
        /// </summary>
        internal static string RemoveDirectory {
            get {
                return ResourceManager.GetString("RemoveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove File.
        /// </summary>
        internal static string RemoveFile {
            get {
                return ResourceManager.GetString("RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Directory.
        /// </summary>
        internal static string Rename_Directory {
            get {
                return ResourceManager.GetString("Rename Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Directory.
        /// </summary>
        internal static string RenameDirectory {
            get {
                return ResourceManager.GetString("RenameDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename File.
        /// </summary>
        internal static string RenameFile {
            get {
                return ResourceManager.GetString("RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request another project.
        /// </summary>
        internal static string RequestAnotherProject {
            get {
                return ResourceManager.GetString("RequestAnotherProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Project.
        /// </summary>
        internal static string RequestProject {
            get {
                return ResourceManager.GetString("RequestProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robinia url prefix.
        /// </summary>
        internal static string RobiniaUrlPrefix {
            get {
                return ResourceManager.GetString("RobiniaUrlPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robinia url prefix is required.
        /// </summary>
        internal static string RobiniaUrlPrefixRequired {
            get {
                return ResourceManager.GetString("RobiniaUrlPrefixRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all children.
        /// </summary>
        internal static string SelectAllChildren {
            get {
                return ResourceManager.GetString("SelectAllChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directories to upload.
        /// </summary>
        internal static string SelectDirectoriesToUpload {
            get {
                return ResourceManager.GetString("SelectDirectoriesToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected item(s).
        /// </summary>
        internal static string SelectedItems {
            get {
                return ResourceManager.GetString("SelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files to upload.
        /// </summary>
        internal static string SelectFilesToUpload {
            get {
                return ResourceManager.GetString("SelectFilesToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        internal static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to see this page. If Your are owner of this project please contact with Administrator.
        /// </summary>
        internal static string StatusCode_403_Description {
            get {
                return ResourceManager.GetString("StatusCode_403_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        internal static string StatusCode_403_Title {
            get {
                return ResourceManager.GetString("StatusCode_403_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested resources could not be found.
        /// </summary>
        internal static string StatusCode_404_Description {
            get {
                return ResourceManager.GetString("StatusCode_404_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string StatusCode_404_Title {
            get {
                return ResourceManager.GetString("StatusCode_404_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This error can happer because:
        ///1. Internal server error
        ///2. Current project references by URL has been blocked, removed or is temporary unavailable
        ///3. Server cannot process current request
        ///
        ///If You uploaded Your project and You see this error at any time please contact with System Administrator.
        /// </summary>
        internal static string StatusCode_500_Data {
            get {
                return ResourceManager.GetString("StatusCode_500_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server encountered error.
        /// </summary>
        internal static string StatusCode_500_Description {
            get {
                return ResourceManager.GetString("StatusCode_500_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        internal static string StatusCode_500_Title {
            get {
                return ResourceManager.GetString("StatusCode_500_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You sure you want to delete page with Id: {0}?.
        /// </summary>
        internal static string Template_ConfirmDeletePage {
            get {
                return ResourceManager.GetString("Template_ConfirmDeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        internal static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &apos;Login&apos; buttons You aggree with our.
        /// </summary>
        internal static string Text_LoginInfo1 {
            get {
                return ResourceManager.GetString("Text_LoginInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic created successfully.
        /// </summary>
        internal static string TopicCreatedSuccessfully {
            get {
                return ResourceManager.GetString("TopicCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic has been deleted successfully.
        /// </summary>
        internal static string TopicDeleteSuccessfully {
            get {
                return ResourceManager.GetString("TopicDeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic does not exists.
        /// </summary>
        internal static string TopicDoesNotExists {
            get {
                return ResourceManager.GetString("TopicDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic updated successfully.
        /// </summary>
        internal static string TopicEditedSuccessfully {
            get {
                return ResourceManager.GetString("TopicEditedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent topic cannot be topic itself.
        /// </summary>
        internal static string TopicParentCannotBeTopicItself {
            get {
                return ResourceManager.GetString("TopicParentCannotBeTopicItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Topics.
        /// </summary>
        internal static string TopicsManage {
            get {
                return ResourceManager.GetString("TopicsManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic updated successfully.
        /// </summary>
        internal static string TopicUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("TopicUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Visitors.
        /// </summary>
        internal static string TotalVisitors {
            get {
                return ResourceManager.GetString("TotalVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total website items count.
        /// </summary>
        internal static string TotalWebsiteItemsCount {
            get {
                return ResourceManager.GetString("TotalWebsiteItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Directories.
        /// </summary>
        internal static string UploadDirectories {
            get {
                return ResourceManager.GetString("UploadDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Directories.
        /// </summary>
        internal static string UploadDirectoryOrDirectories {
            get {
                return ResourceManager.GetString("UploadDirectoryOrDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        internal static string UploadFileOrFiles {
            get {
                return ResourceManager.GetString("UploadFileOrFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        internal static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload files or directories.
        /// </summary>
        internal static string UploadFilesOrDirectories {
            get {
                return ResourceManager.GetString("UploadFilesOrDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more files are invalid. Valid files are .xml documentation and .dll .NET assembly. Total size of all files cannot exceed 16MB.
        /// </summary>
        internal static string ValidationErrorFilesNotXmlOrDotNetAssembly {
            get {
                return ResourceManager.GetString("ValidationErrorFilesNotXmlOrDotNetAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required.
        /// </summary>
        internal static string ValueRequired {
            get {
                return ResourceManager.GetString("ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Visitors (Last 24H).
        /// </summary>
        internal static string Visitors24h {
            get {
                return ResourceManager.GetString("Visitors24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for redirect.
        /// </summary>
        internal static string WaitForRedirect {
            get {
                return ResourceManager.GetString("WaitForRedirect", resourceCulture);
            }
        }
    }
}
