'use client';
import './globals.css'
import { Inter } from 'next/font/google'
import * as React from 'react';
import Navbar from '../../components/navbar';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../../config/theme';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import Footer from '../../components/footer';
import GlobalAppContextProvider from '../../hooks/globalAppContext';
import Link from 'next/link';
import BodyContent from './BodyContent';
import Config from 'config/Config';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

let googleScriptContent =
  `
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XP7D8QMFZK');
`

if (!Config.env.isProduction) {
  googleScriptContent = '';
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-XP7D8QMFZK"></script>
        <script dangerouslySetInnerHTML={{ __html: googleScriptContent }}></script>
        <title>DNDocs | Free .NET Core documentation hosting platform</title>
        <meta name="description" content="Free .NET Core documentation hosting platform" />
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />
      </head>
        <GlobalAppContextProvider>
          <ThemeProvider theme={theme}>
            <BodyContent>{children}</BodyContent>
          </ThemeProvider>
        </GlobalAppContextProvider>
    </html >
  )
}
